version: '3'

services:
  app:
    build: .
    container_name: ${PROJECT_NAME}-app
    restart: always
    environment:
      APP_ENV: ${APP_ENV:-dev}
    ports:
      - "${PROJECT_APP_PORT}:80" # HTTP
    volumes:
      - .:/srv/app:rw,cached
